package ggtCorba.CoordinatorPackage;


/**
* ggtCorba/CoordinatorPackage/noStarters.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Donnerstag, 10. Mai 2012 16:13 Uhr MESZ
*/

public final class noStarters extends org.omg.CORBA.UserException
{
  public String s = null;

  public noStarters ()
  {
    super(noStartersHelper.id());
  } // ctor

  public noStarters (String _s)
  {
    super(noStartersHelper.id());
    s = _s;
  } // ctor


  public noStarters (String $reason, String _s)
  {
    super(noStartersHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class noStarters
