package lagern.LagerfachPackage;

/**
* lagern/LagerfachPackage/invalidCountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class invalidCountHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.LagerfachPackage.invalidCount value = null;

  public invalidCountHolder ()
  {
  }

  public invalidCountHolder (lagern.LagerfachPackage.invalidCount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.LagerfachPackage.invalidCountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.LagerfachPackage.invalidCountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.LagerfachPackage.invalidCountHelper.type ();
  }

}
