package lagern.LagerfachPackage;


/**
* lagern/LagerfachPackage/invalidCount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class invalidCount extends org.omg.CORBA.UserException
{
  public String s = null;

  public invalidCount ()
  {
    super(invalidCountHelper.id());
  } // ctor

  public invalidCount (String _s)
  {
    super(invalidCountHelper.id());
    s = _s;
  } // ctor


  public invalidCount (String $reason, String _s)
  {
    super(invalidCountHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class invalidCount
