package lagern.LagerfachPackage;


/**
* lagern/LagerfachPackage/notEnoughPieces.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class notEnoughPieces extends org.omg.CORBA.UserException
{
  public String s = null;

  public notEnoughPieces ()
  {
    super(notEnoughPiecesHelper.id());
  } // ctor

  public notEnoughPieces (String _s)
  {
    super(notEnoughPiecesHelper.id());
    s = _s;
  } // ctor


  public notEnoughPieces (String $reason, String _s)
  {
    super(notEnoughPiecesHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class notEnoughPieces
