package lagern.LagerfachPackage;

/**
* lagern/LagerfachPackage/notEnoughPiecesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class notEnoughPiecesHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.LagerfachPackage.notEnoughPieces value = null;

  public notEnoughPiecesHolder ()
  {
  }

  public notEnoughPiecesHolder (lagern.LagerfachPackage.notEnoughPieces initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.LagerfachPackage.notEnoughPiecesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.LagerfachPackage.notEnoughPiecesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.LagerfachPackage.notEnoughPiecesHelper.type ();
  }

}
