package lagern.FachPackage;


/**
* lagern/FachPackage/exNotEnoughPieces.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Donnerstag, 29. März 2012 20:04 Uhr MESZ
*/

public final class exNotEnoughPieces extends org.omg.CORBA.UserException
{
  public String s = null;

  public exNotEnoughPieces ()
  {
    super(exNotEnoughPiecesHelper.id());
  } // ctor

  public exNotEnoughPieces (String _s)
  {
    super(exNotEnoughPiecesHelper.id());
    s = _s;
  } // ctor


  public exNotEnoughPieces (String $reason, String _s)
  {
    super(exNotEnoughPiecesHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class exNotEnoughPieces
