package lagern.LagerPackage;


/**
* lagern/LagerPackage/exAlreadyExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Donnerstag, 29. März 2012 20:04 Uhr MESZ
*/

public final class exAlreadyExists extends org.omg.CORBA.UserException
{
  public String s = null;

  public exAlreadyExists ()
  {
    super(exAlreadyExistsHelper.id());
  } // ctor

  public exAlreadyExists (String _s)
  {
    super(exAlreadyExistsHelper.id());
    s = _s;
  } // ctor


  public exAlreadyExists (String $reason, String _s)
  {
    super(exAlreadyExistsHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class exAlreadyExists
