
package hawmetering;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HAWSensorWebservice", targetNamespace = "http://hawmetering/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HAWSensorWebservice {


    /**
     * 
     */
    @WebMethod
    public void blub();

    /**
     * 
     * @param url
     */
    @WebMethod
    public void registerSensor(
        @WebParam(name = "url", partName = "url")
        String url);

    /**
     * 
     */
    @WebMethod
    public void trigger();

}
