
package hawmetering;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HAWSensorWebservice", targetNamespace = "http://hawmetering/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HAWSensorWebservice {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getCoordinatorUrl();

    /**
     * 
     * @param hawmeterChart
     * @param url
     * @throws Exception_Exception
     */
    @WebMethod
    public void registerSensor(
        @WebParam(name = "url", partName = "url")
        String url,
        @WebParam(name = "hawmeterChart", partName = "hawmeterChart")
        String hawmeterChart)
        throws Exception_Exception
    ;

    /**
     * 
     */
    @WebMethod
    public void trigger();

}
