
package hawmetering;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import net.java.dev.jaxb.array.StringArray;
import net.java.dev.jaxb.array.StringArrayArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HAWSensorWebservice", targetNamespace = "http://hawmetering/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    hawmetering.ObjectFactory.class
})
public interface HAWSensorWebservice {


    /**
     * 
     * @param hawmeterUrlsMap
     * @param sensorUrlMap
     */
    @WebMethod
    public void sendUpdate(
        @WebParam(name = "sensorUrlMap", partName = "sensorUrlMap")
        StringArray sensorUrlMap,
        @WebParam(name = "hawmeterUrlsMap", partName = "hawmeterUrlsMap")
        StringArrayArray hawmeterUrlsMap);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getCoordinatorUrl();

    /**
     * 
     * @param hawmeterChart
     * @param url
     * @throws Exception_Exception
     */
    @WebMethod
    public void registerSensor(
        @WebParam(name = "url", partName = "url")
        String url,
        @WebParam(name = "hawmeterChart", partName = "hawmeterChart")
        String hawmeterChart)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void startElection(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void newCoordinator(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     */
    @WebMethod
    public void trigger();

}
