package lagern;


/**
* lagern/LagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Donnerstag, 29. März 2012 20:04 Uhr MESZ
*/

public abstract class LagerPOA extends org.omg.PortableServer.Servant
 implements lagern.LagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("neu", new java.lang.Integer (0));
    _methods.put ("hole", new java.lang.Integer (1));
    _methods.put ("holeLagerListe", new java.lang.Integer (2));
    _methods.put ("aktiviereMonitor", new java.lang.Integer (3));
    _methods.put ("entferneMonitor", new java.lang.Integer (4));
    _methods.put ("quit", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Parameter user zur Kennzeichnung, wer die Aktion aufruft. Dient zur Protokollierung im Monitor.
       case 0:  // lagern/Lager/neu
       {
         try {
           String user = in.read_string ();
           String name = in.read_string ();
           lagern.Fach $result = null;
           $result = this.neu (user, name);
           out = $rh.createReply();
           lagern.FachHelper.write (out, $result);
         } catch (lagern.LagerPackage.exAlreadyExists $ex) {
           out = $rh.createExceptionReply ();
           lagern.LagerPackage.exAlreadyExistsHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // lagern/Lager/hole
       {
         try {
           String user = in.read_string ();
           String name = in.read_string ();
           lagern.Fach $result = null;
           $result = this.hole (user, name);
           out = $rh.createReply();
           lagern.FachHelper.write (out, $result);
         } catch (lagern.LagerPackage.exNotFound $ex) {
           out = $rh.createExceptionReply ();
           lagern.LagerPackage.exNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // lagern/Lager/holeLagerListe
       {
         lagern.Fach $result[] = null;
         $result = this.holeLagerListe ();
         out = $rh.createReply();
         lagern.FachListeHelper.write (out, $result);
         break;
       }

       case 3:  // lagern/Lager/aktiviereMonitor
       {
         lagern.Monitor theMonitor = lagern.MonitorHelper.read (in);
         this.aktiviereMonitor (theMonitor);
         out = $rh.createReply();
         break;
       }

       case 4:  // lagern/Lager/entferneMonitor
       {
         lagern.Monitor theMonitor = lagern.MonitorHelper.read (in);
         this.entferneMonitor (theMonitor);
         out = $rh.createReply();
         break;
       }


  //Dient zum Beenden der Lageranwendung. Sorgt dafuer, dass das Lager und alle registrierten Monitore beendet werden.
       case 5:  // lagern/Lager/quit
       {
         this.quit ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:lagern/Lager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Lager _this() 
  {
    return LagerHelper.narrow(
    super._this_object());
  }

  public Lager _this(org.omg.CORBA.ORB orb) 
  {
    return LagerHelper.narrow(
    super._this_object(orb));
  }


} // class LagerPOA
