
package hawsensor;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HAWSensorWebserviceService", targetNamespace = "http://hawsensor/", wsdlLocation = "http://localhost:1337/hawmetering/sensor?wsdl")
public class HAWSensorWebserviceService
    extends Service
{

    private final static URL HAWSENSORWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(hawsensor.HAWSensorWebserviceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = hawsensor.HAWSensorWebserviceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:1337/hawmetering/sensor?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9998/hawmetering/sensor?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HAWSENSORWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public HAWSensorWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HAWSensorWebserviceService() {
        super(HAWSENSORWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://hawsensor/", "HAWSensorWebserviceService"));
    }

    /**
     * 
     * @return
     *     returns HAWSensorWebservice
     */
    @WebEndpoint(name = "HAWSensorWebservicePort")
    public HAWSensorWebservice getHAWSensorWebservicePort() {
        return super.getPort(new QName("http://hawsensor/", "HAWSensorWebservicePort"), HAWSensorWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HAWSensorWebservice
     */
    @WebEndpoint(name = "HAWSensorWebservicePort")
    public HAWSensorWebservice getHAWSensorWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hawsensor/", "HAWSensorWebservicePort"), HAWSensorWebservice.class, features);
    }

}
