package ggtCorba;


/**
* ggtCorba/CoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Mittwoch, 2. Mai 2012 23:06 Uhr MESZ
*/

public interface CoordinatorOperations 
{
  ggtCorba.Starter[] getStarters ();
  void start (int minProcess, int maxProcess, int minDelay, int maxDelay, int timeout, int ggt, monitor.Monitor mntr) throws ggtCorba.CoordinatorPackage.noStarters, ggtCorba.CoordinatorPackage.calculationInProgress;
  boolean shutdown ();
  boolean isCalculating ();
  void registerStarter (ggtCorba.Starter starter) throws ggtCorba.CoordinatorPackage.starterAlreadyExists;
  void registerProcess (ggtCorba.ggtProcess process, String processName);
  void unregisterStarter (ggtCorba.Starter starter) throws ggtCorba.CoordinatorPackage.starterDoesNotExists;
  void processCalcDone (ggtCorba.ggtProcess process);
} // interface CoordinatorOperations
