package ggtCorba;


/**
* ggtCorba/ggtProcess.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Samstag, 28. April 2012 17:00 Uhr MESZ
*/

public interface ggtProcess extends ggtProcessOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ggtProcess
