package ggtCorba;

/**
* ggtCorba/ggtProcessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Samstag, 28. April 2012 16:31 Uhr MESZ
*/

public final class ggtProcessHolder implements org.omg.CORBA.portable.Streamable
{
  public ggtCorba.ggtProcess value = null;

  public ggtProcessHolder ()
  {
  }

  public ggtProcessHolder (ggtCorba.ggtProcess initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggtCorba.ggtProcessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggtCorba.ggtProcessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggtCorba.ggtProcessHelper.type ();
  }

}
