package ggtCorba;


/**
* ggtCorba/ggtProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Donnerstag, 10. Mai 2012 16:13 Uhr MESZ
*/

public interface ggtProcessOperations 
{
  void initProcess (ggtCorba.ggtProcess left, ggtCorba.ggtProcess right, int startValue, int delay, int timeout, monitor.Monitor mntr);
  void start ();
  void calc (int y, String msgFrom);
  void terminate (String processName, boolean isAllowed);
  String getName ();
  void kill ();
  int getStartValue ();
} // interface ggtProcessOperations
