package ggtCorba;


/**
* ggtCorba/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Mittwoch, 2. Mai 2012 12:42 Uhr MESZ
*/

public interface StarterOperations 
{
  String getName ();
  void createProcesses (int count);
  void killProcesses ();
  void shutdown ();
} // interface StarterOperations
