package ggtCorba;


/**
* ggtCorba/Starter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Mittwoch, 2. Mai 2012 14:46 Uhr MESZ
*/

public interface Starter extends StarterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Starter
