package ggtCorba;


/**
* ggtCorba/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Samstag, 28. April 2012 17:00 Uhr MESZ
*/

public interface StarterOperations 
{
  String getName ();
  void createProcesses (int count);
  void killProcesses ();
  void shutdown ();
} // interface StarterOperations
