package ggtCorba;


/**
* ggtCorba/starterListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Mittwoch, 2. Mai 2012 12:42 Uhr MESZ
*/

public final class starterListHolder implements org.omg.CORBA.portable.Streamable
{
  public ggtCorba.Starter value[] = null;

  public starterListHolder ()
  {
  }

  public starterListHolder (ggtCorba.Starter[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggtCorba.starterListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggtCorba.starterListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggtCorba.starterListHelper.type ();
  }

}
