package lagern.FachPackage;

/**
* lagern/FachPackage/exNotEnoughPiecesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Donnerstag, 29. März 2012 20:04 Uhr MESZ
*/

public final class exNotEnoughPiecesHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.FachPackage.exNotEnoughPieces value = null;

  public exNotEnoughPiecesHolder ()
  {
  }

  public exNotEnoughPiecesHolder (lagern.FachPackage.exNotEnoughPieces initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.FachPackage.exNotEnoughPiecesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.FachPackage.exNotEnoughPiecesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.FachPackage.exNotEnoughPiecesHelper.type ();
  }

}
