package ggt.CoordinatorPackage;


/**
* ggt/CoordinatorPackage/calcInProgress.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Samstag, 28. April 2012 11:26 Uhr MESZ
*/

public final class calcInProgress extends org.omg.CORBA.UserException
{
  public String s = null;

  public calcInProgress ()
  {
    super(calcInProgressHelper.id());
  } // ctor

  public calcInProgress (String _s)
  {
    super(calcInProgressHelper.id());
    s = _s;
  } // ctor


  public calcInProgress (String $reason, String _s)
  {
    super(calcInProgressHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class calcInProgress
