package ggt.CoordinatorPackage;


/**
* ggt/CoordinatorPackage/starterAlreadyExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Donnerstag, 19. April 2012 20:21 Uhr MESZ
*/

public final class starterAlreadyExists extends org.omg.CORBA.UserException
{
  public String s = null;

  public starterAlreadyExists ()
  {
    super(starterAlreadyExistsHelper.id());
  } // ctor

  public starterAlreadyExists (String _s)
  {
    super(starterAlreadyExistsHelper.id());
    s = _s;
  } // ctor


  public starterAlreadyExists (String $reason, String _s)
  {
    super(starterAlreadyExistsHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class starterAlreadyExists
