package lagern;


/**
* lagern/MonitorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Donnerstag, 29. März 2012 20:04 Uhr MESZ
*/

public interface MonitorOperations 
{
  void aktion (String user, String log);
  void quit ();
} // interface MonitorOperations
