package ggt;


/**
* ggt/Coordinator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Donnerstag, 19. April 2012 20:21 Uhr MESZ
*/

public interface Coordinator extends CoordinatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Coordinator
