package ggt;


/**
* ggt/ggtProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Freitag, 27. April 2012 10:45 Uhr MESZ
*/

public interface ggtProcessOperations 
{

  // Name/ID des Prozess im Konstruktor
  void initProcess (ggt.ggtProcess left, ggt.ggtProcess right, int startValue, int delay, int timeout, monitor.Monitor mntr);
  void start ();
  void calc (int y);
  boolean terminate (String processName);
  String getName ();
} // interface ggtProcessOperations
