package ggt;


/**
* ggt/ggtProcess.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Mittwoch, 25. April 2012 10:34 Uhr MESZ
*/

public interface ggtProcess extends ggtProcessOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ggtProcess
