package ggt;


/**
* ggt/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Freitag, 27. April 2012 11:57 Uhr MESZ
*/

public interface StarterOperations 
{
  String getName ();
  void createProcesses (int count);
  void shutdown ();
} // interface StarterOperations
