package ggt;


/**
* ggt/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Donnerstag, 19. April 2012 20:21 Uhr MESZ
*/

public interface StarterOperations 
{
  String getName ();
  void createProcesses (int count);
} // interface StarterOperations
