package ggt;


/**
* ggt/starterListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggt.idl
* Freitag, 27. April 2012 10:45 Uhr MESZ
*/

public final class starterListHolder implements org.omg.CORBA.portable.Streamable
{
  public ggt.Starter value[] = null;

  public starterListHolder ()
  {
  }

  public starterListHolder (ggt.Starter[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggt.starterListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggt.starterListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggt.starterListHelper.type ();
  }

}
