package lagern;


/**
* lagern/_LagerfachStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public class _LagerfachStub extends org.omg.CORBA.portable.ObjectImpl implements lagern.Lagerfach
{

  public String besitzer ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_besitzer", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return besitzer (        );
            } finally {
                _releaseReply ($in);
            }
  } // besitzer

  public void besitzer (String newBesitzer)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_besitzer", true);
                $out.write_string (newBesitzer);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                besitzer (newBesitzer        );
            } finally {
                _releaseReply ($in);
            }
  } // besitzer

  public int anzahl ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_anzahl", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return anzahl (        );
            } finally {
                _releaseReply ($in);
            }
  } // anzahl

  public void einlagern (String user, int anzahl) throws lagern.LagerfachPackage.invalidCount
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("einlagern", true);
                $out.write_string (user);
                $out.write_long (anzahl);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:lagern/Lagerfach/invalidCount:1.0"))
                    throw lagern.LagerfachPackage.invalidCountHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                einlagern (user, anzahl        );
            } finally {
                _releaseReply ($in);
            }
  } // einlagern

  public void auslagern (String user, int anzahl) throws lagern.LagerfachPackage.invalidCount, lagern.LagerfachPackage.notEnoughPieces
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("auslagern", true);
                $out.write_string (user);
                $out.write_long (anzahl);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:lagern/Lagerfach/invalidCount:1.0"))
                    throw lagern.LagerfachPackage.invalidCountHelper.read ($in);
                else if (_id.equals ("IDL:lagern/Lagerfach/notEnoughPieces:1.0"))
                    throw lagern.LagerfachPackage.notEnoughPiecesHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                auslagern (user, anzahl        );
            } finally {
                _releaseReply ($in);
            }
  } // auslagern

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:lagern/Lagerfach:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _LagerfachStub
