package lagern;


/**
* lagern/LagerfaecherListeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class LagerfaecherListeHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public LagerfaecherListeHolder ()
  {
  }

  public LagerfaecherListeHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.LagerfaecherListeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.LagerfaecherListeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.LagerfaecherListeHelper.type ();
  }

}
