package lagern;


/**
* lagern/LagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public interface LagerOperations 
{
  lagern.Lagerfach neu (String besitzer, String name) throws lagern.LagerPackage.alreadyExists;
  lagern.Lagerfach hole (String name) throws lagern.LagerPackage.notFound;
  String[] holeLagerListe ();
  void aktiviereMonitor (String user, lagern.Monitor theMonitor);
  void entferneMonitor (String user, lagern.Monitor theMonitor);
} // interface LagerOperations
