package lagern;

/**
* lagern/LagerfachHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class LagerfachHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.Lagerfach value = null;

  public LagerfachHolder ()
  {
  }

  public LagerfachHolder (lagern.Lagerfach initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.LagerfachHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.LagerfachHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.LagerfachHelper.type ();
  }

}
