package lagern;


/**
* lagern/MonitorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public interface MonitorOperations 
{
  void aktion (String user, String log);
  void quit ();
} // interface MonitorOperations
