package lagern.LagerPackage;

/**
* lagern/LagerPackage/alreadyExistsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class alreadyExistsHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.LagerPackage.alreadyExists value = null;

  public alreadyExistsHolder ()
  {
  }

  public alreadyExistsHolder (lagern.LagerPackage.alreadyExists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.LagerPackage.alreadyExistsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.LagerPackage.alreadyExistsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.LagerPackage.alreadyExistsHelper.type ();
  }

}
