package lagern.LagerPackage;


/**
* lagern/LagerPackage/alreadyExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class alreadyExists extends org.omg.CORBA.UserException
{
  public String s = null;

  public alreadyExists ()
  {
    super(alreadyExistsHelper.id());
  } // ctor

  public alreadyExists (String _s)
  {
    super(alreadyExistsHelper.id());
    s = _s;
  } // ctor


  public alreadyExists (String $reason, String _s)
  {
    super(alreadyExistsHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class alreadyExists
