package lagern.LagerPackage;

/**
* lagern/LagerPackage/notFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class notFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.LagerPackage.notFound value = null;

  public notFoundHolder ()
  {
  }

  public notFoundHolder (lagern.LagerPackage.notFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.LagerPackage.notFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.LagerPackage.notFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.LagerPackage.notFoundHelper.type ();
  }

}
