package lagern.LagerPackage;


/**
* lagern/LagerPackage/notFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* den 25 oktober 2010 kl 15:09 CEST
*/

public final class notFound extends org.omg.CORBA.UserException
{
  public String s = null;

  public notFound ()
  {
    super(notFoundHelper.id());
  } // ctor

  public notFound (String _s)
  {
    super(notFoundHelper.id());
    s = _s;
  } // ctor


  public notFound (String $reason, String _s)
  {
    super(notFoundHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class notFound
